/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "sigs.k8s.io/container-object-storage-interface-api/client/apis/objectstorage/v1alpha1"
	scheme "sigs.k8s.io/container-object-storage-interface-api/client/clientset/versioned/scheme"
)

// BucketClaimsGetter has a method to return a BucketClaimInterface.
// A group's client should implement this interface.
type BucketClaimsGetter interface {
	BucketClaims(namespace string) BucketClaimInterface
}

// BucketClaimInterface has methods to work with BucketClaim resources.
type BucketClaimInterface interface {
	Create(ctx context.Context, bucketClaim *v1alpha1.BucketClaim, opts v1.CreateOptions) (*v1alpha1.BucketClaim, error)
	Update(ctx context.Context, bucketClaim *v1alpha1.BucketClaim, opts v1.UpdateOptions) (*v1alpha1.BucketClaim, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bucketClaim *v1alpha1.BucketClaim, opts v1.UpdateOptions) (*v1alpha1.BucketClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BucketClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BucketClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BucketClaim, err error)
	BucketClaimExpansion
}

// bucketClaims implements BucketClaimInterface
type bucketClaims struct {
	*gentype.ClientWithList[*v1alpha1.BucketClaim, *v1alpha1.BucketClaimList]
}

// newBucketClaims returns a BucketClaims
func newBucketClaims(c *ObjectstorageV1alpha1Client, namespace string) *bucketClaims {
	return &bucketClaims{
		gentype.NewClientWithList[*v1alpha1.BucketClaim, *v1alpha1.BucketClaimList](
			"bucketclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.BucketClaim { return &v1alpha1.BucketClaim{} },
			func() *v1alpha1.BucketClaimList { return &v1alpha1.BucketClaimList{} }),
	}
}
