---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base/

resources:
# Sidecar
- https://raw.githubusercontent.com/container-object-storage-interface/cosi-provisioner-sidecar/master/examples/object-storage-sidecar.yaml

patches:
# Sidecar
- target:
    kind: Deployment
    name: object-storage-provisioner
  patch: |-
    - op: replace
      path: /metadata
      value:
        name: object-storage-provisioner
        labels:
          app: object-storage-provisioner
        namespace: objectstorage-provisioner-ns
- target:
    kind: Secret
    name: object-storage-provisioner
  patch: |-
    - op: replace
      path: /metadata
      value:
        name: object-storage-provisioner
        labels:
          app: object-storage-provisioner
        namespace: objectstorage-provisioner-ns
