apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: provisioner
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-provisioner
spec:
  replicas: 1
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: container-object-storage-interface
      app.kubernetes.io/component: provisioner
      app.kubernetes.io/name: container-object-storage-interface-provisioner
      app.kubernetes.io/version: main
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: container-object-storage-interface
        app.kubernetes.io/component: provisioner
        app.kubernetes.io/name: container-object-storage-interface-provisioner
        app.kubernetes.io/version: main
    spec:
      serviceAccountName: objectstorage-provisioner-sa
      volumes:
      - name: socket
        emptyDir: {}
      containers:
      - name: minio-cosi-driver
        image: $(IMAGE_ORG)/minio-cosi-driver:$(IMAGE_VERSION)
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: objectstorage-provisioner
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
      - name: objectstorage-provisioner-sidecar
        image: $(IMAGE_ORG)/objectstorage-sidecar:$(IMAGE_VERSION)
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: objectstorage-provisioner
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
