---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-provisioner-role
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: provisioner
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-provisioner
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccesses","buckets/status", "bucketaccesses/status"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["secrets", "events"]
  verbs: ["get", "delete", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-provisioner-role-binding
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: provisioner
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-provisioner
subjects:
  - kind: ServiceAccount
    name: objectstorage-provisioner-sa
    namespace: default # must set to default. see https://github.com/kubernetes-sigs/kustomize/issues/1377#issuecomment-694731163
roleRef:
  kind: ClusterRole
  name: objectstorage-provisioner-role
  apiGroup: rbac.authorization.k8s.io
