---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectstorage-provisioner-sa
  namespace: default # must set to default. see https://github.com/kubernetes-sigs/kustomize/issues/1377#issuecomment-694731163
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: provisioner
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-provisioner
