---
apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: provisioner
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-provisioner
type: Opaque
stringData:
  LISTEN_ADDRESS: tcp://0.0.0.0:9000
data:
  # set to space
  S3_ENDPOINT: IA==
  ACCESS_KEY: IA==
  SECRET_KEY: IA==
