/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage.k8s.io/v1alpha1"
)

// FakeBucketAccessInfos implements BucketAccessInfoInterface
type FakeBucketAccessInfos struct {
	Fake *FakeObjectstorageV1alpha1
	ns   string
}

var bucketaccessinfosResource = schema.GroupVersionResource{Group: "objectstorage.k8s.io", Version: "v1alpha1", Resource: "bucketaccessinfos"}

var bucketaccessinfosKind = schema.GroupVersionKind{Group: "objectstorage.k8s.io", Version: "v1alpha1", Kind: "BucketAccessInfo"}

// Get takes name of the bucketAccessInfo, and returns the corresponding bucketAccessInfo object, and an error if there is any.
func (c *FakeBucketAccessInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BucketAccessInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bucketaccessinfosResource, c.ns, name), &v1alpha1.BucketAccessInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessInfo), err
}

// List takes label and field selectors, and returns the list of BucketAccessInfos that match those selectors.
func (c *FakeBucketAccessInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BucketAccessInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bucketaccessinfosResource, bucketaccessinfosKind, c.ns, opts), &v1alpha1.BucketAccessInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BucketAccessInfoList{ListMeta: obj.(*v1alpha1.BucketAccessInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.BucketAccessInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bucketAccessInfos.
func (c *FakeBucketAccessInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bucketaccessinfosResource, c.ns, opts))

}

// Create takes the representation of a bucketAccessInfo and creates it.  Returns the server's representation of the bucketAccessInfo, and an error, if there is any.
func (c *FakeBucketAccessInfos) Create(ctx context.Context, bucketAccessInfo *v1alpha1.BucketAccessInfo, opts v1.CreateOptions) (result *v1alpha1.BucketAccessInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bucketaccessinfosResource, c.ns, bucketAccessInfo), &v1alpha1.BucketAccessInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessInfo), err
}

// Update takes the representation of a bucketAccessInfo and updates it. Returns the server's representation of the bucketAccessInfo, and an error, if there is any.
func (c *FakeBucketAccessInfos) Update(ctx context.Context, bucketAccessInfo *v1alpha1.BucketAccessInfo, opts v1.UpdateOptions) (result *v1alpha1.BucketAccessInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bucketaccessinfosResource, c.ns, bucketAccessInfo), &v1alpha1.BucketAccessInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessInfo), err
}

// Delete takes name of the bucketAccessInfo and deletes it. Returns an error if one occurs.
func (c *FakeBucketAccessInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bucketaccessinfosResource, c.ns, name), &v1alpha1.BucketAccessInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBucketAccessInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bucketaccessinfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BucketAccessInfoList{})
	return err
}

// Patch applies the patch and returns the patched bucketAccessInfo.
func (c *FakeBucketAccessInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BucketAccessInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bucketaccessinfosResource, c.ns, name, pt, data, subresources...), &v1alpha1.BucketAccessInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessInfo), err
}
