/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubernetes-sigs/container-object-storage-interface-api/apis/objectstorage.k8s.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCOSIDrivers implements COSIDriverInterface
type FakeCOSIDrivers struct {
	Fake *FakeObjectstorageV1alpha1
	ns   string
}

var cosidriversResource = schema.GroupVersionResource{Group: "objectstorage.k8s.io", Version: "v1alpha1", Resource: "cosidrivers"}

var cosidriversKind = schema.GroupVersionKind{Group: "objectstorage.k8s.io", Version: "v1alpha1", Kind: "COSIDriver"}

// Get takes name of the cOSIDriver, and returns the corresponding cOSIDriver object, and an error if there is any.
func (c *FakeCOSIDrivers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.COSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cosidriversResource, c.ns, name), &v1alpha1.COSIDriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.COSIDriver), err
}

// List takes label and field selectors, and returns the list of COSIDrivers that match those selectors.
func (c *FakeCOSIDrivers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.COSIDriverList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cosidriversResource, cosidriversKind, c.ns, opts), &v1alpha1.COSIDriverList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.COSIDriverList{ListMeta: obj.(*v1alpha1.COSIDriverList).ListMeta}
	for _, item := range obj.(*v1alpha1.COSIDriverList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cOSIDrivers.
func (c *FakeCOSIDrivers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cosidriversResource, c.ns, opts))

}

// Create takes the representation of a cOSIDriver and creates it.  Returns the server's representation of the cOSIDriver, and an error, if there is any.
func (c *FakeCOSIDrivers) Create(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.CreateOptions) (result *v1alpha1.COSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cosidriversResource, c.ns, cOSIDriver), &v1alpha1.COSIDriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.COSIDriver), err
}

// Update takes the representation of a cOSIDriver and updates it. Returns the server's representation of the cOSIDriver, and an error, if there is any.
func (c *FakeCOSIDrivers) Update(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.UpdateOptions) (result *v1alpha1.COSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cosidriversResource, c.ns, cOSIDriver), &v1alpha1.COSIDriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.COSIDriver), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCOSIDrivers) UpdateStatus(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.UpdateOptions) (*v1alpha1.COSIDriver, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cosidriversResource, "status", c.ns, cOSIDriver), &v1alpha1.COSIDriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.COSIDriver), err
}

// Delete takes name of the cOSIDriver and deletes it. Returns an error if one occurs.
func (c *FakeCOSIDrivers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cosidriversResource, c.ns, name), &v1alpha1.COSIDriver{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCOSIDrivers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cosidriversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.COSIDriverList{})
	return err
}

// Patch applies the patch and returns the patched cOSIDriver.
func (c *FakeCOSIDrivers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.COSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cosidriversResource, c.ns, name, pt, data, subresources...), &v1alpha1.COSIDriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.COSIDriver), err
}
