/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubernetes-sigs/container-object-storage-interface-api/apis/objectstorage.k8s.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBucketAccessRequests implements BucketAccessRequestInterface
type FakeBucketAccessRequests struct {
	Fake *FakeObjectstorageV1alpha1
	ns   string
}

var bucketaccessrequestsResource = schema.GroupVersionResource{Group: "objectstorage.k8s.io", Version: "v1alpha1", Resource: "bucketaccessrequests"}

var bucketaccessrequestsKind = schema.GroupVersionKind{Group: "objectstorage.k8s.io", Version: "v1alpha1", Kind: "BucketAccessRequest"}

// Get takes name of the bucketAccessRequest, and returns the corresponding bucketAccessRequest object, and an error if there is any.
func (c *FakeBucketAccessRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BucketAccessRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bucketaccessrequestsResource, c.ns, name), &v1alpha1.BucketAccessRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessRequest), err
}

// List takes label and field selectors, and returns the list of BucketAccessRequests that match those selectors.
func (c *FakeBucketAccessRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BucketAccessRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bucketaccessrequestsResource, bucketaccessrequestsKind, c.ns, opts), &v1alpha1.BucketAccessRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BucketAccessRequestList{ListMeta: obj.(*v1alpha1.BucketAccessRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.BucketAccessRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bucketAccessRequests.
func (c *FakeBucketAccessRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bucketaccessrequestsResource, c.ns, opts))

}

// Create takes the representation of a bucketAccessRequest and creates it.  Returns the server's representation of the bucketAccessRequest, and an error, if there is any.
func (c *FakeBucketAccessRequests) Create(ctx context.Context, bucketAccessRequest *v1alpha1.BucketAccessRequest, opts v1.CreateOptions) (result *v1alpha1.BucketAccessRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bucketaccessrequestsResource, c.ns, bucketAccessRequest), &v1alpha1.BucketAccessRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessRequest), err
}

// Update takes the representation of a bucketAccessRequest and updates it. Returns the server's representation of the bucketAccessRequest, and an error, if there is any.
func (c *FakeBucketAccessRequests) Update(ctx context.Context, bucketAccessRequest *v1alpha1.BucketAccessRequest, opts v1.UpdateOptions) (result *v1alpha1.BucketAccessRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bucketaccessrequestsResource, c.ns, bucketAccessRequest), &v1alpha1.BucketAccessRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBucketAccessRequests) UpdateStatus(ctx context.Context, bucketAccessRequest *v1alpha1.BucketAccessRequest, opts v1.UpdateOptions) (*v1alpha1.BucketAccessRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bucketaccessrequestsResource, "status", c.ns, bucketAccessRequest), &v1alpha1.BucketAccessRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessRequest), err
}

// Delete takes name of the bucketAccessRequest and deletes it. Returns an error if one occurs.
func (c *FakeBucketAccessRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bucketaccessrequestsResource, c.ns, name), &v1alpha1.BucketAccessRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBucketAccessRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bucketaccessrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BucketAccessRequestList{})
	return err
}

// Patch applies the patch and returns the patched bucketAccessRequest.
func (c *FakeBucketAccessRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BucketAccessRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bucketaccessrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BucketAccessRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketAccessRequest), err
}
