---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: objectstorage-provisioner-ns

resources:
# Namespace
- ns.yaml
# Sidecar
- https://raw.githubusercontent.com/container-object-storage-interface/cosi-provisioner-sidecar/master/examples/object-storage-sidecar.yaml
