# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3000s
options:
  substitution_option: ALLOW_LOOSE
steps:
- name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20221214-1b4dd4d69a"
  entrypoint: make
  args: ['build']
  env:
  - GIT_TAG=${_GIT_TAG}
  - PULL_BASE_REF=${_PULL_BASE_REF}
- name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20221214-1b4dd4d69a"
  entrypoint: make
  args: ['push']
  env:
  - GIT_TAG=${_GIT_TAG}
  - PULL_BASE_REF=${_PULL_BASE_REF}
