---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: objectstorage-provisioner-ns

commonAnnotations:
  cosi.storage.k8s.io/authors: "Kubernetes Authors"
  cosi.storage.k8s.io/license: "Apache V2"
  cosi.storage.k8s.io/support: "https://github.com/kubernetes-sigs/container-object-storage-api"

commonLabels:
  app.kubernetes.io/part-of: container-object-storage-interface
  app.kubernetes.io/component: provisioner
  app.kubernetes.io/version: main
  app.kubernetes.io/name: container-object-storage-interface-provisioner

configMapGenerator: 
- name: objectstorage-provisioner-config
  env: resources/objectstorage-provisioner.properties         
generatorOptions:         
  disableNameSuffixHash: true
  labels:                    
    generated-by: "kustomize"

resources:
- resources/ns.yaml
- resources/sa.yaml
- resources/rbac.yaml
- resources/secret.yaml
- resources/deployment.yaml
- resources/minio.yaml

configurations:
 - resources/kustomizeconfig.yaml

vars:
  - name: IMAGE_ORG
    objref:
      name: objectstorage-provisioner-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.OBJECTSTORAGE_PROVISIONER_IMAGE_ORG
  - name: IMAGE_VERSION
    objref:
      name: objectstorage-provisioner-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.OBJECTSTORAGE_PROVISIONER_IMAGE_VERSION
