#
# BUILDER
#
FROM docker.io/library/golang:1.22 AS builder

WORKDIR /buildroot

# Cache deps before building and copying source, so that we don't need to re-download
# as much and so that source changes don't invalidate our downloaded layer.
COPY client/ client/
COPY proto/ proto/
COPY internal/ internal/

COPY {{COMPONENT}}/go.mod {{COMPONENT}}/go.mod
COPY {{COMPONENT}}/go.sum {{COMPONENT}}/go.sum

WORKDIR /buildroot/{{COMPONENT}}
RUN go mod download

WORKDIR /buildroot

COPY {{COMPONENT}}/cmd/ {{COMPONENT}}/cmd/
COPY {{COMPONENT}}/pkg/ {{COMPONENT}}/pkg/

WORKDIR /buildroot/{{COMPONENT}}

RUN CGO_ENABLED=0 go build -o /buildroot/artifacts/{{COMPONENT}} cmd/*.go


#
# FINAL IMAGE
#
FROM gcr.io/distroless/static:nonroot

LABEL maintainers="Kubernetes Authors"
LABEL description="COSI {{COMPONENT}}"

LABEL org.opencontainers.image.title="COSI {{COMPONENT}}"
LABEL org.opencontainers.image.description="Container Object Storage Interface (COSI) {{COMPONENT}}"
LABEL org.opencontainers.image.source="https://github.com/kubernetes-sigs/container-object-storage-interface-api/{{COMPONENT}}"
LABEL org.opencontainers.image.licenses="APACHE-2.0"

WORKDIR /
COPY --from=builder /buildroot/artifacts/{{COMPONENT}} .
USER 65532:65532

ENTRYPOINT ["/{{COMPONENT}}"]
