/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage/v1alpha1"
)

// BucketInfoLister helps list BucketInfos.
// All objects returned here must be treated as read-only.
type BucketInfoLister interface {
	// List lists all BucketInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BucketInfo, err error)
	// Get retrieves the BucketInfo from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.BucketInfo, error)
	BucketInfoListerExpansion
}

// bucketInfoLister implements the BucketInfoLister interface.
type bucketInfoLister struct {
	indexer cache.Indexer
}

// NewBucketInfoLister returns a new BucketInfoLister.
func NewBucketInfoLister(indexer cache.Indexer) BucketInfoLister {
	return &bucketInfoLister{indexer: indexer}
}

// List lists all BucketInfos in the indexer.
func (s *bucketInfoLister) List(selector labels.Selector) (ret []*v1alpha1.BucketInfo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BucketInfo))
	})
	return ret, err
}

// Get retrieves the BucketInfo from the index for a given name.
func (s *bucketInfoLister) Get(name string) (*v1alpha1.BucketInfo, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("bucketinfo"), name)
	}
	return obj.(*v1alpha1.BucketInfo), nil
}
