/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BucketListerExpansion allows custom methods to be added to
// BucketLister.
type BucketListerExpansion interface{}

// BucketAccessListerExpansion allows custom methods to be added to
// BucketAccessLister.
type BucketAccessListerExpansion interface{}

// BucketAccessClassListerExpansion allows custom methods to be added to
// BucketAccessClassLister.
type BucketAccessClassListerExpansion interface{}

// BucketClaimListerExpansion allows custom methods to be added to
// BucketClaimLister.
type BucketClaimListerExpansion interface{}

// BucketClaimNamespaceListerExpansion allows custom methods to be added to
// BucketClaimNamespaceLister.
type BucketClaimNamespaceListerExpansion interface{}

// BucketClassListerExpansion allows custom methods to be added to
// BucketClassLister.
type BucketClassListerExpansion interface{}
