---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
# CRDs
- github.com/kubernetes-sigs/container-object-storage-interface-api/crds

resources:
# Controller
- sa.yaml
- rbac.yaml
- deployment.yaml
