---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-controller-role
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["bucketrequests", "bucketaccessrequests"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccess"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["bucketclass","bucketaccessclass"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:objectstorage-controller
subjects:
  - kind: ServiceAccount
    name: objectstorage-controller-sa
    namespace: objectstorage-system
roleRef:
  kind: ClusterRole
  name: objectstorage-controller-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-controller
  namespace: objectstorage-system
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-controller
  namespace: objectstorage-system
subjects:
  - kind: ServiceAccount
    name: objectstorage-controller-sa
    namespace: objectstorage-system
roleRef:
  kind: Role
  name: objectstorage-controller
  apiGroup: rbac.authorization.k8s.io
