---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectstorage-controller-sa
  namespace: objectstorage-system
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-controller
