/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage/v1alpha1"
)

// FakeBucketInfos implements BucketInfoInterface
type FakeBucketInfos struct {
	Fake *FakeObjectstorageV1alpha1
}

var bucketinfosResource = schema.GroupVersionResource{Group: "objectstorage.k8s.io", Version: "v1alpha1", Resource: "bucketinfos"}

var bucketinfosKind = schema.GroupVersionKind{Group: "objectstorage.k8s.io", Version: "v1alpha1", Kind: "BucketInfo"}

// Get takes name of the bucketInfo, and returns the corresponding bucketInfo object, and an error if there is any.
func (c *FakeBucketInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BucketInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bucketinfosResource, name), &v1alpha1.BucketInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketInfo), err
}

// List takes label and field selectors, and returns the list of BucketInfos that match those selectors.
func (c *FakeBucketInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BucketInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bucketinfosResource, bucketinfosKind, opts), &v1alpha1.BucketInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BucketInfoList{ListMeta: obj.(*v1alpha1.BucketInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.BucketInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bucketInfos.
func (c *FakeBucketInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bucketinfosResource, opts))
}

// Create takes the representation of a bucketInfo and creates it.  Returns the server's representation of the bucketInfo, and an error, if there is any.
func (c *FakeBucketInfos) Create(ctx context.Context, bucketInfo *v1alpha1.BucketInfo, opts v1.CreateOptions) (result *v1alpha1.BucketInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bucketinfosResource, bucketInfo), &v1alpha1.BucketInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketInfo), err
}

// Update takes the representation of a bucketInfo and updates it. Returns the server's representation of the bucketInfo, and an error, if there is any.
func (c *FakeBucketInfos) Update(ctx context.Context, bucketInfo *v1alpha1.BucketInfo, opts v1.UpdateOptions) (result *v1alpha1.BucketInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bucketinfosResource, bucketInfo), &v1alpha1.BucketInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketInfo), err
}

// Delete takes name of the bucketInfo and deletes it. Returns an error if one occurs.
func (c *FakeBucketInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bucketinfosResource, name, opts), &v1alpha1.BucketInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBucketInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bucketinfosResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BucketInfoList{})
	return err
}

// Patch applies the patch and returns the patched bucketInfo.
func (c *FakeBucketInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BucketInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bucketinfosResource, name, pt, data, subresources...), &v1alpha1.BucketInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BucketInfo), err
}
