version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups: # batch updates together for fewer dependabot PRs
      golang-dependencies:
        patterns:
          - "github.com/golang*"
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
      github-dependencies:
        patterns:
          - "github.com*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
