# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3000s
substitutions:
  _IMAGE_NAME: 'gcr.io/k8s-staging-sig-storage/objectstorage-controller'
  _IMAGE_TAG: 'canary'
options:
  substitution_option: ALLOW_LOOSE
steps:
- name: "gcr.io/k8s-testimages/gcb-docker-gcloud:v20220617-174ad91c3a"
  entrypoint: make
  args: ['build']
- name: "gcr.io/k8s-testimages/gcb-docker-gcloud:v20220617-174ad91c3a"
  entrypoint: make
  args: ['push']