# GCloud build docs: https://cloud.google.com/cloud-build/docs/build-config
# Build console:
#   https://console.cloud.google.com/gcr/images/k8s-staging-test-infra/global/objectstorage-controller
timeout: 3000s
options:
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
substitutions:
  # GCloud provides som built-in substitution vars:
  #   https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
  # K8s provides custom substitutions _GIT_TAG and _PULL_BASE_REF:
  #   https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md#custom-substitutions
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'master'
steps:
  # it is extremely unclear in GCR docs whether standard gcr.io/cloud-builders/docker builds allow
  # building multi-arch image manifests as 'docker buildx build' does; therefore, use make buildx
  # target to be certain multi-arch images are released
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230522-312425ae46'
    entrypoint: make
    args: ['buildx']
    env:
      - BUILDX_PLATFORMS='linux/amd64,linux/arm64'
      - IMAGE_TAG='gcr.io/k8s-staging-sig-storage/objectstorage-controller:${_GIT_TAG}'
      - BUILD_ARGS='--tag "gcr.io/k8s-staging-sig-storage/objectstorage-controller:latest"'
images:
  - gcr.io/k8s-staging-sig-storage/objectstorage-controller:${_GIT_TAG}
  - gcr.io/k8s-staging-sig-storage/objectstorage-controller:latest
