# GCloud build docs: https://cloud.google.com/cloud-build/docs/build-config
# Builds go to: https://console.cloud.google.com/gcr/images/k8s-staging-test-infra/global/
timeout: 3000s
options:
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
substitutions:
  # GCloud provides som built-in substitution vars:
  #   https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
  # K8s provides custom substitutions _GIT_TAG and _PULL_BASE_REF:
  #   https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md#custom-substitutions
  _GIT_TAG: '12345'  # e.g., vYYYYMMDD-hash, vYYYYMMDD-tag, or vYYYYMMDD-tag-n-ghash
  _PULL_BASE_REF: 'master'  # e.g., master or release-0.2 for a PR merge, or v0.2 for a tag
steps:
  # based on simple build example
  # https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md
  - name: gcr.io/cloud-builders/docker
    # entrypoint: # docker by default
    args:
      - buildx
      - build
      - --platform="linux/amd64,linux/arm64"
      - --tag=gcr.io/k8s-staging-sig-storage/objectstorage-controller:${_GIT_TAG}
      - --tag=gcr.io/k8s-staging-sig-storage/objectstorage-controller:latest
      - .
images:
  - gcr.io/k8s-staging-sig-storage/objectstorage-controller:${_GIT_TAG}
  - gcr.io/k8s-staging-sig-storage/objectstorage-controller:latest
