/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage.k8s.io/v1alpha1"
	scheme "sigs.k8s.io/container-object-storage-interface-api/clientset/scheme"
)

// BucketAccessInfosGetter has a method to return a BucketAccessInfoInterface.
// A group's client should implement this interface.
type BucketAccessInfosGetter interface {
	BucketAccessInfos(namespace string) BucketAccessInfoInterface
}

// BucketAccessInfoInterface has methods to work with BucketAccessInfo resources.
type BucketAccessInfoInterface interface {
	Create(ctx context.Context, bucketAccessInfo *v1alpha1.BucketAccessInfo, opts v1.CreateOptions) (*v1alpha1.BucketAccessInfo, error)
	Update(ctx context.Context, bucketAccessInfo *v1alpha1.BucketAccessInfo, opts v1.UpdateOptions) (*v1alpha1.BucketAccessInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BucketAccessInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BucketAccessInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BucketAccessInfo, err error)
	BucketAccessInfoExpansion
}

// bucketAccessInfos implements BucketAccessInfoInterface
type bucketAccessInfos struct {
	client rest.Interface
	ns     string
}

// newBucketAccessInfos returns a BucketAccessInfos
func newBucketAccessInfos(c *ObjectstorageV1alpha1Client, namespace string) *bucketAccessInfos {
	return &bucketAccessInfos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the bucketAccessInfo, and returns the corresponding bucketAccessInfo object, and an error if there is any.
func (c *bucketAccessInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BucketAccessInfo, err error) {
	result = &v1alpha1.BucketAccessInfo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BucketAccessInfos that match those selectors.
func (c *bucketAccessInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BucketAccessInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BucketAccessInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bucketAccessInfos.
func (c *bucketAccessInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a bucketAccessInfo and creates it.  Returns the server's representation of the bucketAccessInfo, and an error, if there is any.
func (c *bucketAccessInfos) Create(ctx context.Context, bucketAccessInfo *v1alpha1.BucketAccessInfo, opts v1.CreateOptions) (result *v1alpha1.BucketAccessInfo, err error) {
	result = &v1alpha1.BucketAccessInfo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bucketAccessInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a bucketAccessInfo and updates it. Returns the server's representation of the bucketAccessInfo, and an error, if there is any.
func (c *bucketAccessInfos) Update(ctx context.Context, bucketAccessInfo *v1alpha1.BucketAccessInfo, opts v1.UpdateOptions) (result *v1alpha1.BucketAccessInfo, err error) {
	result = &v1alpha1.BucketAccessInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		Name(bucketAccessInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bucketAccessInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the bucketAccessInfo and deletes it. Returns an error if one occurs.
func (c *bucketAccessInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bucketAccessInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched bucketAccessInfo.
func (c *bucketAccessInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BucketAccessInfo, err error) {
	result = &v1alpha1.BucketAccessInfo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("bucketaccessinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
