/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubernetes-sigs/container-object-storage-interface-api/apis/objectstorage.k8s.io/v1alpha1"
	scheme "github.com/kubernetes-sigs/container-object-storage-interface-api/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// COSIDriversGetter has a method to return a COSIDriverInterface.
// A group's client should implement this interface.
type COSIDriversGetter interface {
	COSIDrivers(namespace string) COSIDriverInterface
}

// COSIDriverInterface has methods to work with COSIDriver resources.
type COSIDriverInterface interface {
	Create(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.CreateOptions) (*v1alpha1.COSIDriver, error)
	Update(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.UpdateOptions) (*v1alpha1.COSIDriver, error)
	UpdateStatus(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.UpdateOptions) (*v1alpha1.COSIDriver, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.COSIDriver, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.COSIDriverList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.COSIDriver, err error)
	COSIDriverExpansion
}

// cOSIDrivers implements COSIDriverInterface
type cOSIDrivers struct {
	client rest.Interface
	ns     string
}

// newCOSIDrivers returns a COSIDrivers
func newCOSIDrivers(c *ObjectstorageV1alpha1Client, namespace string) *cOSIDrivers {
	return &cOSIDrivers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cOSIDriver, and returns the corresponding cOSIDriver object, and an error if there is any.
func (c *cOSIDrivers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.COSIDriver, err error) {
	result = &v1alpha1.COSIDriver{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cosidrivers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of COSIDrivers that match those selectors.
func (c *cOSIDrivers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.COSIDriverList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.COSIDriverList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cosidrivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cOSIDrivers.
func (c *cOSIDrivers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cosidrivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cOSIDriver and creates it.  Returns the server's representation of the cOSIDriver, and an error, if there is any.
func (c *cOSIDrivers) Create(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.CreateOptions) (result *v1alpha1.COSIDriver, err error) {
	result = &v1alpha1.COSIDriver{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cosidrivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cOSIDriver).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cOSIDriver and updates it. Returns the server's representation of the cOSIDriver, and an error, if there is any.
func (c *cOSIDrivers) Update(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.UpdateOptions) (result *v1alpha1.COSIDriver, err error) {
	result = &v1alpha1.COSIDriver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cosidrivers").
		Name(cOSIDriver.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cOSIDriver).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *cOSIDrivers) UpdateStatus(ctx context.Context, cOSIDriver *v1alpha1.COSIDriver, opts v1.UpdateOptions) (result *v1alpha1.COSIDriver, err error) {
	result = &v1alpha1.COSIDriver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cosidrivers").
		Name(cOSIDriver.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cOSIDriver).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cOSIDriver and deletes it. Returns an error if one occurs.
func (c *cOSIDrivers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cosidrivers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cOSIDrivers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cosidrivers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cOSIDriver.
func (c *cOSIDrivers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.COSIDriver, err error) {
	result = &v1alpha1.COSIDriver{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cosidrivers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
